### PR TITLE
Respect config values from genesis

### LINKED ISSUE #95: Changing config consensus to tendermint doesn't affect anything
It looks like that the default config is always used and user-defined config is ignored.

So `HelloWorld` application doesn't work with Tendermint consensus

### PR DESCRIPTION
**Pull request by JekaMas**
closes #95

### CODE REVIEW

**Comment by aneequesafdar** [comment]
Can we please not push the helloworld changes for testing, please remove them. Otherwise, LGTM

File: eth/config.go [hunk 1]
```diff
@@ -61,8 +61,6 @@ var DefaultConfig = Config{
 		Blocks:     20,
 		Percentile: 60,
 	},
-	Istanbul:    *istanbul.DefaultConfig,
```
Comment (aneequesafdar) [inline eth/config.go]: `Istanbul istanbul.Config` `Tendermint tendermint.Config` should also be removed from the `eth.Config` definition in `eth/config.go`

File: eth/config.go [hunk 2]
```diff
@@ -61,8 +61,6 @@ var DefaultConfig = Config{
...
-	OpenNetwork: false,
```
Comment (aneequesafdar) [inline eth/config.go]: Why should this also be removed?

Comment (JekaMas) [reply eth/config.go]: I've just thought, why not remove useless values from the config.

File: cmd/autonity/chaincmd.go [hunk 3]
```diff
@@ -219,6 +224,59 @@ func initGenesis(ctx *cli.Context) error {
...
+		}
+		if len(genesis.Config.Tendermint.Deployer) == 0 || genesis.Config.Tendermint.Deployer == (common.Address{}) {
+			genesis.Config.Tendermint.Deployer = tendermint.DefaultConfig.Deployer
+		}
+		if genesis.Config.Tendermint.Epoch == 0 {
+			genesis.Config.Tendermint.Epoch = tendermint.DefaultConfig.Epoch
+		}
+	}
+}
+
```
Comment (aneequesafdar) [inline cmd/autonity/chaincmd.go]: Just an idea, instead of checking again their empty values would it be better to check that the fields are not default values? It could be the case that user-defined `Epoch = 0 and BlockPeriod = 0` but then they are set to default values, is this something we want?

File: eth/config.go (hunk 2 above)
Comment (aneequesafdar) [reply eth/config.go]: ok it should be fine since the default value for boolean is false

File: cmd/autonity/chaincmd.go (hunk 3 above)
Comment (JekaMas) [reply cmd/autonity/chaincmd.go]: `Epoch = 0` and `BlockPeriod = 0` are not very meaningful if the one wants to have an epoch each block, he or she will use `Epoch = 1`.
The solution could be to use reference types `*int` instead of `int`.
