### PR TITLE
Fix roundchange data races

### LINKED ISSUE #136: Refactor `latestPendingUnminedBlock` in tendermint/core.go
`latestPendingUnminedBlock` keeps track of the potential future proposal, we want `latestPendingUnminedBlock` to be the current height and most updated at the time of proposal so that we have latest transactions in the block. There is an event `NewUnmineBlockEvent` which signals to the consensus layer that a new "unmined" block is available and this event's handler updates the `core.latestPendingUnminedBlock`.

If the `c.latestPendingUnminedBlock == nil` at startup or `latestPendingUnminedBlock` height is not the same then start round will wait for a `NewUnminedBlockEvent`.

The current implementation uses a channel and boolean values to coordinate, however, it is not ideal. So we need to refactor how `c.latestPendingUnminedBlock` is updated.

### PR DESCRIPTION
**Pull request by aneequesafdar**
closes rest of the data races: #142 #143 
Also closes #136

### CODE REVIEW

File: consensus/tendermint/core/core.go [hunk 1]
```diff
@@ -284,12 +277,22 @@ func (c *core) startRound(round *big.Int) {
...
 
+	// Wait for c.handleNewUnminedBlockEvent() go routine to update c.latestPendingUnminedBlock
 	// Only wait for new unmined block if latestPendingUnminedBlock is nil or fo previous height
-	c.latestPendingUnminedBlockMu.RLock()
-	isMined := c.latestPendingUnminedBlock == nil || c.latestPendingUnminedBlock.Number() != c.currentRoundState.Height()
-	c.latestPendingUnminedBlockMu.RUnlock()
-	if isMined {
-		<-c.unminedBlockCh
+	if c.checkLatestPendingUnminedBlock() {
+		ticker := time.NewTicker(100 * time.Millisecond)
```
Comment (JekaMas) [inline consensus/tendermint/core/core.go]: May its better to subscribe to 'newBlockEvent'(it's not a precise name)? Timers are ok for timeouts, gc, networking, retries.

File: consensus/tendermint/core/handler.go [hunk 2]
```diff
@@ -11,90 +11,118 @@ import (
...
+		if r := recover(); r != nil {
+			debug.PrintStack()
+
+			c.logger.Crit("panic in core.handleNewUnminedBlockEvent", "panic", r)
+		}
+	}()
+
+	for e := range c.newUnminedBlockEventSub.Chan() {
+		// TODO: check is probably unnecessary
+		if newUnminedBlockEvent, ok := e.Data.(tendermint.NewUnminedBlockEvent); ok {
```
Comment (JekaMas) [inline consensus/tendermint/core/handler.go]: Yeap, we can remove the check

File: consensus/tendermint/core/core.go (hunk 1 above)
Comment (aneequesafdar) [reply consensus/tendermint/core/core.go]: Ok I will think about it a bit more

File: consensus/tendermint/core/handler.go (hunk 2 above)
Comment (aneequesafdar) [reply consensus/tendermint/core/handler.go]: Actually, I just realised that the casting is required. I will remove the todo.

Comment (JekaMas) [reply consensus/tendermint/core/handler.go]: The casting is required, however the check is not.

File: consensus/tendermint/core/core.go (hunk 1 above)
Comment (aneequesafdar) [reply consensus/tendermint/core/core.go]: I don't want to create another message event for `NewUnminedBlockEvent`, channels should be sufficient, so its either this or the previous solution.

 The general idea is to have 2 goroutines, where one is always updating `latestUnminePendingBlock`, while the other is handling consensus event sequentially and anytime `latestUnminePendingBlock` is nil or of different height, we want to block and wait for the other goroutine. Which is why we need both locks and channels, lock to make sure `latestUnminePendingBlock` correctly set when the condition (`c.latestPendingUnminedBlock == nil || c.latestPendingUnminedBlock.Number().Int64() != c.currentRoundState.Height().Int64()`) is false, and channel to synchronise when the condition is true. In order to get rid of the channel, I set a ticker to check every 100 * Millisecond, which I know is not ideal because it could be set in between 100 ms.

The other problem is that passing the new unmined block through the channel is not useful because then we will be setting it twice, so passing it through the channel will mean that we will block one go routine and it will remain blocked until `startRound()` is called in the other goroutine. We can think about using buffered channels but then we will have to manage the priority which is already being done by `storeUnminedBlockMsg` and `processPendingUnminedBlock`. So, I cannot think of another way without changing the consensus architecture for handling events (which IMO is unnecessary for #136).

File: consensus/tendermint/core/handler.go (hunk 2 above)
Comment (aneequesafdar) [reply consensus/tendermint/core/handler.go]: I see, I will update

File: consensus/tendermint/core/core.go (hunk 1 above)
Comment (JekaMas) [reply consensus/tendermint/core/core.go]: Ok, lets live with this solution for some time. I still think that this should be done without timers, flags, mutexes but only with one channel. However, we can wait for a while and think about it later.

**Comment by JekaMas** [comment]
Are tests with 'race' flag green?

**Comment by aneequesafdar** [comment]
Yes, but its not mining properly but that is another issue to fix

**Comment by JekaMas** [comment]
My congratulations! now you have the first experience working with data races in golang. It's an important step.

**Comment by aneequesafdar** [comment]
also closes #141
